// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EmmetVS
{
    internal sealed partial class Vsix
    {
        public const string Id = "EmmetVS.45ebdcc6-7813-4798-be08-7fbe376c5d47";
        public const string Name = "EmmetVS";
        public const string Description = @"Supercharge your Visual Studio environment with the power of Emmet! Effortlessly expand abbreviations into complex HTML/XML and CSS code snippets. Streamline your web development process and elevate your coding efficiency like never before.";
        public const string Language = "en-US";
        public const string Version = "0.0.1";
        public const string Author = "Amadej Glasenčnik";
        public const string Tags = "visual-studio, vsix, emmet, html, css, xml, snippets, tools";
    }
}
