// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EmmetVS
{
    internal sealed partial class Vsix
    {
        public const string Id = "EmmetVS.45ebdcc6-7813-4798-be08-7fbe376c5d47";
        public const string Name = "EmmetVS";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Amadej Glasenčnik";
        public const string Tags = "";
    }
}
