// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EmmetVS
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string EmmetVSString = "cac45f96-4a68-4790-98b3-aa7525c67da5";
        public static Guid EmmetVS = new Guid(EmmetVSString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int EmmetToolsSnippetsMenu = 0x1001;
        public const int AbbreviationAndExpansionGroup = 0x2001;
        public const int TagBalancingGroup = 0x2002;
        public const int TagAndHTMLManagementGroup = 0x2003;
        public const int NavigationGroup = 0x2004;
        public const int SelectionGroup = 0x2005;
        public const int CommentingAndCodePresentationGroup = 0x2006;
        public const int NumericAndMathOperationsGroup = 0x2007;
        public const int NumericGroup = 0x2008;
        public const int ImageAndDataEncodingGroup = 0x2009;
        public const int ExpandAbbreviationCommand = 0x3001;
        public const int WrapWithAbbreviationCommand = 0x3002;
        public const int BalanceOutwardCommand = 0x3003;
        public const int BalanceInwardCommand = 0x3004;
        public const int GoToMatchingPairCommand = 0x3005;
        public const int SplitJoinTagCommand = 0x3006;
        public const int RemoveTagCommand = 0x3007;
        public const int MergeLinesCommand = 0x3008;
        public const int NextEditPointCommand = 0x3009;
        public const int PreviousEditPointCommand = 0x3010;
        public const int SelectNextItemCommand = 0x3011;
        public const int SelectPreviousItemCommand = 0x3012;
        public const int ToggleCommentCommand = 0x3013;
        public const int ReflectCSSValueCommand = 0x3014;
        public const int UpdateImageSizeCommand = 0x3015;
        public const int EvaluateMathExpressionCommand = 0x3016;
        public const int IncrementByOneCommand = 0x3017;
        public const int DecrementByOneCommand = 0x3018;
        public const int IncrementByPointOneCommand = 0x3019;
        public const int DecrementByPointOneCommand = 0x3020;
        public const int IncrementByTenCommand = 0x3021;
        public const int DecrementByTenCommand = 0x3022;
        public const int EncodeDecodeImageToDataURLCommand = 0x3023;
    }
}